baseURL = "https://danielries.github.io/CSS_ProjectB/"
title = "The Actor Network"
description = "Welcome to our project page! Here you can find all the information about our project."
relativeURLs = true
theme = "theme" 
[params]
    authors = ["Daniel Ries", "Christian Ong Hansen", "Kavus Latifi Yaghin"]
    notebook = "/explainer-notebook.html"
    data = "https://drive.google.com"
    github = "https://github.com/danielries/CSS_ProjectB"
    [[params.nav]]
        label = "Data"
        link = "/data-description"
    [[params.nav]]
        label = "Network"
        link = "/network-analysis"
    [[params.nav]]
        label = "Text"
        link = "/text-analysis"

